import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { Navbar } from "../components/layout/Navbar";
import Providers from "../types/Providers";
import { MathJaxContext } from "better-react-mathjax";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mathJaxConfig = {
  loader: { load: ["input/asciimath", "output/chtml"] },
  tex: {
    inlineMath: [["$", "$"], ["\\(", "\\)"]],
    displayMath: [["$$", "$$"], ["\\[", "\\]"]],
  }
};
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          {/* لفي الـ Navbar والـ main بـ MathJaxContext */}
          <MathJaxContext config={mathJaxConfig}>
            <Navbar />
            <main>
              {children}
            </main>
            <Toaster richColors position="top-center" />
          </MathJaxContext>
        </Providers>
      </body>
    </html>
  );
}
